org: tmaximini
app: apollo-lambda-app
service: apollo-lambda
provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-1
iamRoleStatements:
  Effect: 'Allow'
  Action:
    - 'dynamodb:GetItem'
    - 'dynamodb:PutItem'
    - 'dynamodb:Scan'
  Recource: '*'
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: index.graphqlHandler
    events:
      - http:
          path: graphql
          method: get
          cors: true
          integration: lambda-proxy